### ISSUE TITLE
Ensure Dependencies are Complete Before OpsCenter Provision

### ISSUE THREAD

**Issue by benofben** [DSPN/google-deployment-manager-dse#3]
We need to ensure that the nodes are all started, have java installed, etc before OpsCenter tries to provision them.  It's unclear how to do that today.

**Comment by benofben** [comment]
Currently using a sleep statement to work around this.  The google guys are investigating a better solution as of 10/29/15.

**Comment by benofben** [comment]
Noticed that the console exits before the opscenter startup script has completed running.  This behavior may not be desirable.

**Comment by vfgomes** [comment]
One way we talked about doing this is through references. So you would need a method that generates the reference strings of the low level GCP resources based on your inputs. I believe that something like this could do the job (I haven't tested this though):

def GenerateReferencesList(context):
  reference_list = []
  n_of_copies = context.properties['nodesPerZone']
  dep_name = context.env['deployment']
  for zone in context.properties['zones']:
    for idx in range(1, n_of_copies + 1)
        node_name = '$(ref.%s.selfLink)' % dep_name + '-service-' + zone + '-' + idx + '-vm'
        reference_list.append(node_name)
  return ' '.join(reference_list)


Then you can call this method to return the concatenated string as a value in your metadata

**Comment by benofben** [comment]
I made a couple minor changes and just pushed the code up to github.  I'm testing it now...

**Comment by benofben** [comment]
We currently have references which ensure the nodes are physically provisioned prior to running OpsCenter provision.  We also have a sleep statement.  This attempts to ensure the nodes are given enough time to install Java prior to the provision.  This isn't ideal, but is apparently the best we can do in the platform currently.  

When a new version of OpsCenter provisions Java itself, this issue will be fully resolved.

**Comment by benofben** [comment]
Moving away from OpsCenter provisioning to shell scripts instead.  There are still going to be dependencies to manage, but that should be simpler.  

Those scripts are here: https://github.com/DSPN/install-dse
